apiVersion: v1
kind: Secret
metadata:
  name: rancher-private-tls
  namespace: cattle-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # Replace this block with the real certificate for rancher.<domain>
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # Replace this block with the private key that matches tls.crt
    -----END PRIVATE KEY-----
