apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rke2-harvester.fullname" . }}-cloud-config
  namespace: rke2
type: Opaque
stringData:
  userdata: |
{{ include "rke2-harvester.userData" . | indent 4 }}
