apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  name: vlan2003
  namespace: hvst-mgmt
spec:
  ipv4Config:
    serverIP: 192.168.10.2
    cidr: 192.168.10.0/24
    pool:
      start: 192.168.10.3
      end: 192.168.10.253
      exclude:
      - 192.168.10.5
    router: 192.168.10.1
    dns:
    - 192.168.10.1
    leaseTime: 300
  networkName: hvst-mgmt/vlan2003