apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  name: vlan12
  namespace: default
spec:
  ipv4Config:
    serverIP: 172.16.3.10
    cidr: 172.16.3.0/24
    pool:
      start: 172.16.3.50
      end: 172.16.3.100
    router: 172.16.3.1
    dns:
    - 172.16.3.1
    leaseTime: 300
  networkName: default/vm-network
