{{- if .Values.grafanaIntegration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deepflow-datasource
  namespace: {{ .Values.grafanaIntegration.datasourceNamespace }}
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/name: harvester-network-monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  deepflow-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.grafanaIntegration.datasourceName }}
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-server.{{ .Release.Namespace }}.svc:{{ .Values.deepflow.ports.api }}
        isDefault: {{ .Values.grafanaIntegration.datasourceIsDefault | default false }}
        editable: true
        jsonData:
          timeInterval: 30s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deepflow-dashboards
  namespace: {{ .Values.grafanaIntegration.dashboardsNamespace }}
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: harvester-network-monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  deepflow-network-overview.json: |
{{ tpl (.Files.Get "dashboards/deepflow-network-overview.json") . | indent 4 }}
{{- end }}
